[package]
name = "splunk-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
colored = "2.0"
cfg-if = "1.0"
winit = "0.28"
raw-window-handle = "0.5"
ash = "0.37"
ash-window = "0.12"
nalgebra = "0.32"
nalgebra-glm = "0.18"
rapier3d = "0.17"
rapier2d = "0.17"
image = "0.24"
imgui = "0.11"
imgui-rs-vulkan-renderer = "1.9.0"
gpu-allocator = "0.22"
